name: release
on:
  push:
    branches:
      - main
env:
  version: 1.0.1
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          tar -czf code-${{ env.version }}.tar.gz *
          ls -l
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.DEVOPS_TOKEN }}
          tag_name: ${{ env.version }}
          name: release ${{ env.version }}
          files: code-${{ env.version }}.tar.gz